# Author: Paul Ventisei
# Date: 19th October 2014
# Routing for the Rowing-Competition-Network
# including URL routing, versions, static file uploads, etc. See
# https://developers.google.com/appengine/docs/python/config/appconfig
# for details on how this file works in google app engine.

# named application id in google app engine as rowing-competition-network

application: rowing-competition-network
version: 1
runtime: python27
api_version: 1
threadsafe: yes

# Builtins provide handlers for common application functions. See
# https://developers.google.com/appengine/docs/python/config/appconfig#Python_app_yaml_Builtin_handlers
# for a list of other builtins.
# TODO: List any other builtins that you wish to use.
builtins:
- remote_api: on

# Before the application can receive certain messages, it must be
# configured to enable the appropriate service. The 'warmup' service enables
# warmup requests and the 'mail' service enables receipt and sending of emails
# See https://developers.google.com/appengine/docs/python/config/appconfig#Python_app_yaml_Inbound_services
# for a list of other inbound services.
# TODO:look to see if there is an inbound or outbound service for twitter.

inbound_services:
- warmup
- mail
# - twitter

# Third party libraries that are included in the App Engine SDK must be listed
# here if you want to use them. See
# https://developers.google.com/appengine/docs/python/tools/libraries27 for
# a list of libraries included in the SDK. Third party libs that are *not* part
# of the App Engine SDK don't need to be listed here, instead add them to your
# project directory, either as a git submodule or as a plain subdirectory.
# Note that dependencies must be located in your project directory - packages
# installed in the Python environment are not loaded by the App Engine development
# server or deployment tools.
# TODO: List any other App Engine SDK libs you may need here.
libraries:
- name: webapp2
  version: latest #TODO consider changing this to specific version for stability
- name: jinja2
  version: latest #TODO consider changing to specific version for stability
- name: markupsafe
  version: latest
- name: setuptools
  version: "0.6c11"
- name: lxml
  version: '2.3'



# Handlers tell App Engine how to route requests to your application.
handlers:
# This handler catches all requests that don't match a previous handler.

- url: /images
  static_dir: images

- url: /css
  static_dir: css


- url: /.*
  script: main.application

