/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLObservedtimesRowTimePackageClockSyncReply.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   observedtimes/v1
// Description:
//   ObservedTimes API v1. This API allows the GET method to get a collection of
//   observed times since the last time the user asked for a list and a POST
//   method to record new times
// Classes:
//   GTLObservedtimesRowTimePackageClockSyncReply (0 custom class methods, 3 custom properties)

#import "GTLObservedtimesRowTimePackageClockSyncReply.h"

// ----------------------------------------------------------------------------
//
//   GTLObservedtimesRowTimePackageClockSyncReply
//

@implementation GTLObservedtimesRowTimePackageClockSyncReply
@dynamic clientTime, diffInMs, serverTime;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"clientTime" : @"client_time",
    @"diffInMs" : @"diff_in_ms",
    @"serverTime" : @"server_time"
  };
  return map;
}

@end
