/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLObservedtimes.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   observedtimes/v1
// Description:
//   ObservedTimes API v1. This API allows the GET method to get a collection of
//   observed times since the last time the user asked for a list and a POST
//   method to record new times

#import "GTLObservedtimesConstants.h"

#import "GTLObservedtimesRowTimePackageClockSyncReply.h"
#import "GTLObservedtimesRowTimePackageClockSyncRequest.h"
#import "GTLObservedtimesRowTimePackageCrew.h"
#import "GTLObservedtimesRowTimePackageCrewList.h"
#import "GTLObservedtimesRowTimePackageEvent.h"
#import "GTLObservedtimesRowTimePackageEventList.h"
#import "GTLObservedtimesRowTimePackageObservedTime.h"
#import "GTLObservedtimesRowTimePackageObservedTimeList.h"
#import "GTLObservedtimesRowTimePackageStage.h"

#import "GTLQueryObservedtimes.h"
#import "GTLServiceObservedtimes.h"
