/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLObservedtimesRowTimePackageClockSyncReply.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   observedtimes/v1
// Description:
//   ObservedTimes API v1. This API allows the GET method to get a collection of
//   observed times since the last time the user asked for a list and a POST
//   method to record new times
// Classes:
//   GTLObservedtimesRowTimePackageClockSyncReply (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

// ----------------------------------------------------------------------------
//
//   GTLObservedtimesRowTimePackageClockSyncReply
//

// used to reply with the server time and comparison to the client time

@interface GTLObservedtimesRowTimePackageClockSyncReply : GTLObject
@property (nonatomic, retain) GTLDateTime *clientTime;
@property (nonatomic, retain) NSNumber *diffInMs;  // doubleValue
@property (nonatomic, retain) GTLDateTime *serverTime;
@end
