/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLObservedtimesRowTimePackageObservedTime.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   observedtimes/v1
// Description:
//   ObservedTimes API v1. This API allows the GET method to get a collection of
//   observed times since the last time the user asked for a list and a POST
//   method to record new times
// Classes:
//   GTLObservedtimesRowTimePackageObservedTime (0 custom class methods, 7 custom properties)

#import "GTLObservedtimesRowTimePackageObservedTime.h"

// ----------------------------------------------------------------------------
//
//   GTLObservedtimesRowTimePackageObservedTime
//

@implementation GTLObservedtimesRowTimePackageObservedTime
@dynamic crew, eventId, obsType, stage, time, timeId, timestamp;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"eventId" : @"event_id",
    @"obsType" : @"obs_type",
    @"timeId" : @"time_id"
  };
  return map;
}

@end
