/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLObservedtimesRowTimePackageCrewList.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   observedtimes/v1
// Description:
//   ObservedTimes API v1. This API allows the GET method to get a collection of
//   observed times since the last time the user asked for a list and a POST
//   method to record new times
// Classes:
//   GTLObservedtimesRowTimePackageCrewList (0 custom class methods, 2 custom properties)

#import "GTLObservedtimesRowTimePackageCrewList.h"

#import "GTLObservedtimesRowTimePackageCrew.h"

// ----------------------------------------------------------------------------
//
//   GTLObservedtimesRowTimePackageCrewList
//

@implementation GTLObservedtimesRowTimePackageCrewList
@dynamic crews, eventId;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"eventId" : @"event_id"
  };
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"crews" : [GTLObservedtimesRowTimePackageCrew class]
  };
  return map;
}

@end
