/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLObservedtimes_Sources.m
//
// This file can be compiled into projects to avoid adding the individual
// source files for this service.
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   observedtimes/v1
// Description:
//   ObservedTimes API v1. This API allows the GET method to get a collection of
//   observed times since the last time the user asked for a list and a POST
//   method to record new times

#import "GTLObservedtimesConstants.m"

#import "GTLObservedtimesRowTimePackageClockSyncReply.m"
#import "GTLObservedtimesRowTimePackageClockSyncRequest.m"
#import "GTLObservedtimesRowTimePackageCrew.m"
#import "GTLObservedtimesRowTimePackageCrewList.m"
#import "GTLObservedtimesRowTimePackageEvent.m"
#import "GTLObservedtimesRowTimePackageEventList.m"
#import "GTLObservedtimesRowTimePackageObservedTime.m"
#import "GTLObservedtimesRowTimePackageObservedTimeList.m"
#import "GTLObservedtimesRowTimePackageStage.m"

#import "GTLQueryObservedtimes.m"
#import "GTLServiceObservedtimes.m"
