/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLObservedtimesRowTimePackageStage.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   observedtimes/v1
// Description:
//   ObservedTimes API v1. This API allows the GET method to get a collection of
//   observed times since the last time the user asked for a list and a POST
//   method to record new times
// Classes:
//   GTLObservedtimesRowTimePackageStage (0 custom class methods, 2 custom properties)

#import "GTLObservedtimesRowTimePackageStage.h"

// ----------------------------------------------------------------------------
//
//   GTLObservedtimesRowTimePackageStage
//

@implementation GTLObservedtimesRowTimePackageStage
@dynamic label, stageIndex;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"stageIndex" : @"stage_index"
  };
  return map;
}

@end
