/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLObservedtimesRowTimePackageCrew.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   observedtimes/v1
// Description:
//   ObservedTimes API v1. This API allows the GET method to get a collection of
//   observed times since the last time the user asked for a list and a POST
//   method to record new times
// Classes:
//   GTLObservedtimesRowTimePackageCrew (0 custom class methods, 11 custom properties)

#import "GTLObservedtimesRowTimePackageCrew.h"

#import "GTLObservedtimesRowTimePackageStage.h"

// ----------------------------------------------------------------------------
//
//   GTLObservedtimesRowTimePackageCrew
//

@implementation GTLObservedtimesRowTimePackageCrew
@dynamic category, cox, crewId, crewName, crewNumber, division, endTimeLocal,
         picFile, rowerCount, stages, startTimeLocal;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"crewId" : @"crew_id",
    @"crewName" : @"crew_name",
    @"crewNumber" : @"crew_number",
    @"endTimeLocal" : @"end_time_local",
    @"picFile" : @"pic_file",
    @"rowerCount" : @"rower_count",
    @"startTimeLocal" : @"start_time_local"
  };
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"stages" : [GTLObservedtimesRowTimePackageStage class]
  };
  return map;
}

@end
