/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLObservedtimesRowTimePackageEvent.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   observedtimes/v1
// Description:
//   ObservedTimes API v1. This API allows the GET method to get a collection of
//   observed times since the last time the user asked for a list and a POST
//   method to record new times
// Classes:
//   GTLObservedtimesRowTimePackageEvent (0 custom class methods, 4 custom properties)

#import "GTLObservedtimesRowTimePackageEvent.h"

// ----------------------------------------------------------------------------
//
//   GTLObservedtimesRowTimePackageEvent
//

@implementation GTLObservedtimesRowTimePackageEvent
@dynamic eventDate, eventDesc, eventId, eventName;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"eventDate" : @"event_date",
    @"eventDesc" : @"event_desc",
    @"eventId" : @"event_id",
    @"eventName" : @"event_name"
  };
  return map;
}

@end
