/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLObservedtimesRowTimePackageObservedTimeList.h
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   observedtimes/v1
// Description:
//   ObservedTimes API v1. This API allows the GET method to get a collection of
//   observed times since the last time the user asked for a list and a POST
//   method to record new times
// Classes:
//   GTLObservedtimesRowTimePackageObservedTimeList (0 custom class methods, 3 custom properties)

#if GTL_BUILT_AS_FRAMEWORK
  #import "GTL/GTLObject.h"
#else
  #import "GTLObject.h"
#endif

@class GTLObservedtimesRowTimePackageObservedTime;

// ----------------------------------------------------------------------------
//
//   GTLObservedtimesRowTimePackageObservedTimeList
//

// Used to provide a list of Observed times since last request for a specific
// event

@interface GTLObservedtimesRowTimePackageObservedTimeList : GTLObject
@property (nonatomic, copy) NSString *eventId;
@property (nonatomic, retain) GTLDateTime *lastTimestamp;

// used to store an observered time from a user for a specific Crew.
@property (nonatomic, retain) NSArray *times;  // of GTLObservedtimesRowTimePackageObservedTime

@end
