/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLObservedtimesRowTimePackageObservedTimeList.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   observedtimes/v1
// Description:
//   ObservedTimes API v1. This API allows the GET method to get a collection of
//   observed times since the last time the user asked for a list and a POST
//   method to record new times
// Classes:
//   GTLObservedtimesRowTimePackageObservedTimeList (0 custom class methods, 3 custom properties)

#import "GTLObservedtimesRowTimePackageObservedTimeList.h"

#import "GTLObservedtimesRowTimePackageObservedTime.h"

// ----------------------------------------------------------------------------
//
//   GTLObservedtimesRowTimePackageObservedTimeList
//

@implementation GTLObservedtimesRowTimePackageObservedTimeList
@dynamic eventId, lastTimestamp, times;

+ (NSDictionary *)propertyToJSONKeyMap {
  NSDictionary *map = @{
    @"eventId" : @"event_id",
    @"lastTimestamp" : @"last_timestamp"
  };
  return map;
}

+ (NSDictionary *)arrayPropertyToClassMap {
  NSDictionary *map = @{
    @"times" : [GTLObservedtimesRowTimePackageObservedTime class]
  };
  return map;
}

@end
