/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLObservedtimesConstants.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   observedtimes/v1
// Description:
//   ObservedTimes API v1. This API allows the GET method to get a collection of
//   observed times since the last time the user asked for a list and a POST
//   method to record new times

#import "GTLObservedtimesConstants.h"

// Authorization scope
NSString * const kGTLAuthScopeObservedtimesUserinfoEmail = @"https://www.googleapis.com/auth/userinfo.email";
