/* This file was generated by the ServiceGenerator.
 * The ServiceGenerator is Copyright (c) 2016 Google Inc.
 */

//
//  GTLServiceObservedtimes.m
//

// ----------------------------------------------------------------------------
// NOTE: This file is generated from Google APIs Discovery Service.
// Service:
//   observedtimes/v1
// Description:
//   ObservedTimes API v1. This API allows the GET method to get a collection of
//   observed times since the last time the user asked for a list and a POST
//   method to record new times
// Classes:
//   GTLServiceObservedtimes (0 custom class methods, 0 custom properties)

#import "GTLObservedtimes.h"

@implementation GTLServiceObservedtimes

#if DEBUG
// Method compiled in debug builds just to check that all the needed support
// classes are present at link time.
+ (NSArray *)checkClasses {
  NSArray *classes = @[
    [GTLQueryObservedtimes class],
    [GTLObservedtimesRowTimePackageClockSyncReply class],
    [GTLObservedtimesRowTimePackageClockSyncRequest class],
    [GTLObservedtimesRowTimePackageCrew class],
    [GTLObservedtimesRowTimePackageCrewList class],
    [GTLObservedtimesRowTimePackageEvent class],
    [GTLObservedtimesRowTimePackageEventList class],
    [GTLObservedtimesRowTimePackageObservedTime class],
    [GTLObservedtimesRowTimePackageObservedTimeList class],
    [GTLObservedtimesRowTimePackageStage class]
  ];
  return classes;
}
#endif  // DEBUG

- (instancetype)init {
  self = [super init];
  if (self) {
    // Version from discovery.
    self.apiVersion = @"v1";

    // From discovery.  Where to send JSON-RPC.
    // Turn off prettyPrint for this service to save bandwidth (especially on
    // mobile). The fetcher logging will pretty print.
    self.rpcURL = [NSURL URLWithString:@"https://rowtime-26.appspot.com/_ah/api/rpc?prettyPrint=false"];
  }
  return self;
}

@end
